# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81953334f5119237b1e91c88348f49f4a16076e6456aa85671af2353619006159cacd108b32f7ca6f4dde9c15ee4e85d904aaf967112ae3ecc61039e391993e4
  facebook_app_id: <%=ENV["FACEBOOK_APP_ID"]%>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  aws_app_id: <%= ["AWS_ACCESS_KEY_ID"] %>
  aws_app_secret: <%= ["AWS_SECRET_ACCESS_KEY"] %>


test:
  secret_key_base: 8b6b92ea70d080e88d85b9a3781b33fd5232e68e7aa61eb28629c9aa4d6e3f2e93371d687e261d0924f505fd06c42bca250015c87b8cc629a32cf478ebf10347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%=ENV["FACEBOOK_APP_ID"]%>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  aws_app_id: <%= ["AWS_ACCESS_KEY_ID"] %>
  aws_app_secret: <%= ["AWS_SECRET_ACCESS_KEY"] %>


config.paperclip_defaults = {
  :storage => :s3,
  :s3_credentials => {
    :bucket => ENV['S3_BUCKET_NAME'],
    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  }
}
